Repository con/duct, pull requests merged in 2024-10, with the labels that each got.

#191 Move all logic into single file
  .bumpversion.cfg
  setup.cfg
  src/con_duct/__init__.py
  src/con_duct/__main__.py
  test/test_execution.py
Labels: semver-minor

#195 Report $USER as .user, and store actual numeric UID as .uid
  src/con_duct/__main__.py
  test/test_report.py
Labels: semver-minor, release

#196 BF: Do not rely on having sources under ./src and __main__.py to be executable
  test/test_execution.py
Labels: semver-patch

#182 Add ps stat counter
  src/con_duct/__main__.py
  test/test_aggregation.py
  test/test_report.py
Labels: semver-minor

#164 Create structure for full con-duct suite
  .update-readme-help.py
  README.md
  setup.cfg
  src/con_duct/suite.py
  test/test_suite.py
Labels: semver-minor

#199 Drop Python 3.8, which is EOL
  .github/workflows/release.yml
  .github/workflows/test.yaml
  setup.cfg
Labels: semver-minor

#201 Add start and end time to info.json
  src/con_duct/__main__.py
Labels: semver-minor

#198 Add `con-duct plot` with matplotlib backend
  .github/workflows/readme-updated.yaml
  README.md
  setup.cfg
  src/con_duct/suite/main.py
  src/con_duct/suite/plot.py
  src/con_duct/suite/pprint_json.py
  test/data/mriqc-example/info.json
  test/data/mriqc-example/usage.json
  test/test_suite.py
  tox.ini
Labels: semver-minor

#202 Add testing for Python 3.13
  .github/workflows/test.yaml
  setup.cfg
  test/test_execution.py
  tox.ini
Labels: semver-minor, release
