Repository con/duct, pull requests merged in 2024-05, with the labels that each got.

#18 Handle the outputs logic, run monitoring in thread, and make record types configurable
  .github/workflows/test.yaml
  .gitignore
  setup.cfg
  smoke-tests.sh
  src/duct.py
  test/test_prepare_outputs.py
  test_logs.py
  tox.ini
Labels: tests, minor

#29 Refactor: Introducing... TailPipe!
  .chatgpt/2024-04-21.md
  .chatgpt/2024-04-22.md
  .chatgpt/2024-04-23.md
  src/duct.py
  test/cat_to_err.py
  test/test_aggregation.py
  test/test_helpers.py
  test/test_prepare_outputs.py
  test/test_tailpipe.py
  test/utils.py
  test_logs.py
  tox.ini
Labels: patch

#33 Refactor start sampling
  src/duct.py
Labels: minor

#35 Release from main not master here
  .github/workflows/release.yml
Labels: internal
