Repository con/duct, pull requests merged in 2024-08, with the labels that each got.

#139 RF: no shebang since file is no longer can be executed
  src/con_duct/__main__.py
Labels: semver-patch

#138 ENH: give "typical" shell behavior when command is not found to be executed
  src/con_duct/__main__.py
  test/test_execution.py
Labels: semver-minor

#141 RF+BF: make explicit wall_clock_time separate from elapsed_time
  src/con_duct/__main__.py
  test/test_report.py
Labels: semver-minor

#147 Revert back to original smon + blacken and logging
  src/con_duct/__main__.py
  test/test_report.py
Labels: bug, semver-patch

#156 Check that each PR has one of the semver labels
  .github/workflows/labels.yaml
Labels: semver-tests

#161 Add direct pytest usage to CONTRIBUTING
  CONTRIBUTING.rst
Labels: semver-documentation, release

#166 Add tests for correct handling of args
  test/test_arg_parsing.py
Labels: semver-tests

#167 Argparse abbreviation affects and breaks cmd args
  src/con_duct/__main__.py
  test/test_arg_parsing.py
Labels: semver-patch
