Repository con/duct, pull requests merged in 2024-09, with the labels that each got.

#168 Add output files and schema version to info.json
  src/con_duct/__init__.py
  src/con_duct/__main__.py
Labels: semver-minor

#169 Modify exit code if cmd terminated by signal
  src/con_duct/__main__.py
  test/test_execution.py
  test/test_report.py
Labels: semver-minor

#175 (Re)add etime and cmd into process stats
  src/con_duct/__main__.py
  test/test_report.py
Labels: semver-minor, release

#177 Catchup to actual version for auto releases
  .bumpversion.cfg
Labels: release, semver-internal

#179 Fix operator precedence involving or and addition
  src/con_duct/__main__.py
  test/test_report.py
Labels: semver-patch

#180 BF: Fix sample aggregation
  src/con_duct/__main__.py
  test/test_aggregation.py
  test/test_report.py
Labels: semver-patch, release

#183 Add custom formatter conversion flags and colors based on datalad ls
  README.md
  src/con_duct/__main__.py
  test/test_execution.py
  test/test_formatter.py
  test/test_report.py
Labels: semver-minor, release
