Repository con/duct, pull requests merged in 2025-05, with the labels that each got.

#264 Collect working directory for execution summary
  src/con_duct/__main__.py
  src/con_duct/suite/ls.py
  test/test_aggregation.py
  test/test_execution.py
  test/test_formatter.py
  test/test_report.py
Labels: enhancement, semver-minor, release

#267 Bugfix: do not truncate ps output
  src/con_duct/__main__.py
Labels: semver-patch

#270 Bolt on mergify support to get summaries from CI reported
  .github/workflows/test.yaml
Labels: semver-tests

#269 Allow con-duct ls to function back to schema 0.2.0
  src/con_duct/suite/ls.py
  test/test_ls.py
  test/test_suite.py
Labels: semver-patch, release
