Repository con/duct, pull requests merged in 2025-09, with the labels that each got.

#292 con-duct plot should accept info.json in addition to usage.json
  src/con_duct/suite/plot.py
  test/data/mriqc-example/info.json
  test/test_suite.py
Labels: semver-minor

#295 List a version in "duct is executing" log message
  src/con_duct/__main__.py
Labels: semver-patch

#293 Handle noninteractive matplotlib backends
  src/con_duct/suite/plot.py
  test/test_suite.py
Labels: semver-minor

#300 plot: allow for -o in addition to --output
  src/con_duct/suite/main.py
Labels: enhancement, semver-patch
